default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: time_entry_sys_development
  username: reynan
  password: admin2016
test:
  <<: *default
  database: time_entry_sys_test
  username: reynan
  password: admin2016
  
production:
  <<: *default
  database: time_entry_sys_production
  username: gmlsdbuser
  password: admin2015

staging:
  <<: *default
  database: time_entry_sys_staging
  username: gmlsdbuser
  password: admin2015